int8 GET_STANDARD_ANALOG_IN = 1
int8 GET_STANDARD_ANALOG_OUT = 2
int8 GET_STANDARD_DIGITAL_IN= 3
int8 GET_STANDARD_DIGITAL_OUT= 4
int8 SET_STANDARD_ANALOG_OUT = 5
int8 SET_STANDARD_DIGITAL_OUT= 6
int8 GET_ARML_TOOL_ANALOG_IN = 7
int8 GET_ARML_TOOL_ANALOG_OUT = 8
int8 GET_ARML_TOOL_DIGITAL_IN= 9
int8 GET_ARML_TOOL_DIGITAL_OUT= 10
int8 SET_ARML_TOOL_ANALOG_OUT = 11
int8 SET_ARML_TOOL_DIGITAL_OUT= 12
int8 GET_ARMR_TOOL_ANALOG_IN = 13
int8 GET_ARMR_TOOL_ANALOG_OUT = 14
int8 GET_ARMR_TOOL_DIGITAL_IN= 15
int8 GET_ARMR_TOOL_DIGITAL_OUT= 16
int8 SET_ARMR_TOOL_ANALOG_OUT = 17
int8 SET_ARMR_TOOL_DIGITAL_OUT= 18
int8 fun
int8 pin
float32 state
---
float32 state
int8 success
